#!/usr/bin/env python3
"""
Inline the welcome email into the Edge Function, from one source of truth.

The email is authored in docs/email/welcome.{html,txt}. The `welcome` Edge
Function needs that content at deploy time, and a hand-copied fork would drift —
so this generates supabase/functions/welcome/email.ts from those files. Nothing
in email.ts is authored by hand.

    python tools/bundle-email.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
html = (ROOT / "docs" / "email" / "welcome.html").read_text(encoding="utf-8")
text = (ROOT / "docs" / "email" / "welcome.txt").read_text(encoding="utf-8")
SUBJECT = "You're set up with Kilroy \U0001f44b"

out = ROOT / "supabase" / "functions" / "welcome" / "email.ts"
out.write_text(
    "// GENERATED by tools/bundle-email.py from docs/email/welcome.{html,txt} — do not edit.\n"
    f"export const SUBJECT = {json.dumps(SUBJECT, ensure_ascii=False)};\n"
    f"export const HTML = {json.dumps(html, ensure_ascii=False)};\n"
    f"export const TEXT = {json.dumps(text, ensure_ascii=False)};\n",
    encoding="utf-8",
)
print(f"wrote {out.relative_to(ROOT)}  ({out.stat().st_size:,} bytes)")
